name = "chefriendsapp"
compatibility_date = "2026-01-24"
pages_build_output_dir = "dist"

# KV namespace for waitlist emails
[[kv_namespaces]]
binding = "WAITLIST"
id = "1158feba68cf4ab494e0f77d51142eaa"
